### ISSUE TITLE
Add decorator so that only admins can add new shows

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#2]
### Expected behavior
Add a decorator so that only admins of the website can add shows in the website. Add this decorator to the add_movie view function and AddShowView class. The html also needs to be changed so that only admins can see the option to add movie and add show in the navbar.

### Current behavior
All users can add movies to the website presently.

**Comment by VishalMinj** [comment]
Is this one assigned ? If not then I'd like to contribute on this one

**Comment by smt96700** [comment]
Hi @eleensmathew , I hope you are doing well. I would like to contribute to this project by working on this issue. Could you please  assign it to me?

**Comment by VishalMinj** [comment]
I'm working on this issue.

**Comment by VishalMinj** [comment]
Hello @eleensmathew, 
I'd like to discuss my solution, that is to use the base User class as admin which I'll login with the help of a overridden admin site.
To check if the admin is login I'll apply the login decorator on the  add_movie function. Please correct me if I am overcomplicating any thing

**Comment by eleensmathew** [comment]
Ya that makes sense. Go for it👍

**Comment by VishalMinj** [comment]
Also I am running in an error, which as far as my interpretation suggests - you cant pass context/dictionary with redirect function. Any possible work around to this error?

**Comment by eleensmathew** [comment]
What does the dictionary contain?

**Comment by VishalMinj** [comment]
Well in this particular case the redirect is working internally so I cant say any thing clearly
![image](https://github.com/user-attachments/assets/7f726753-fc68-44c0-9ea4-6b207d1bb4b0)
  
I've also encountered this error while adding a movie from the main repo
![image](https://github.com/user-attachments/assets/d813d672-4508-444a-a31c-38174b205074)
![image](https://github.com/user-attachments/assets/ebf88185-b8c5-4b6f-9e2d-5b908937fd0a)

I tried looking around for ways but "no context with redirect" that was suggested by stackover flow

**Comment by eleensmathew** [comment]
Have you added the view in the urls? I think maybe your errors are related to url.

**Comment by VishalMinj** [comment]
Hey! I made some hit and trials in the settings with the LOGIN URLS, and the decorator seems to be working. Before I configure the html do you need a logout button?

**Comment by eleensmathew** [comment]
No need for logout. I'll make that into a separate issue.

**Comment by VishalMinj** [comment]
Okay, Here's the final preview

1. Navbar prior to admin login 
![image](https://github.com/user-attachments/assets/a76e586f-1a36-46b7-9e3c-3af5f23fb370)

2. Since there is no access to adding movies you either have to append add_movie in url or use admin_login as base url to launch the admin login pannel
![image](https://github.com/user-attachments/assets/9f739d01-f669-4778-879d-f352854192ef)

3. To login admin you'll need a superuser id 

4. upon login the add_movie page will be rendered along with the add_movie section
![image](https://github.com/user-attachments/assets/effaa6b9-8a57-49c3-9867-e4400fd68851)

!One drawback with my implementation is that there is an extra admin site page which the admin can access although i've not registered any of the models in it
![image](https://github.com/user-attachments/assets/369abe66-3694-40a5-b316-fac05283c082)

**Comment by eleensmathew** [comment]
Theres a way to modify the nav bar  so that admin sees different options compared to other users. Check this out https://stackoverflow.com/questions/41781104/how-to-display-specific-navbar-when-logged-in

**Comment by eleensmathew** [comment]
I am not sure what exactly you have done in the admin page. When you make your pull request I'll review it.
